-- AlterTable
ALTER TABLE "CallUsage" ALTER COLUMN "audioMinutes" SET DEFAULT 0,
ALTER COLUMN "audioMinutes" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "videoMinutes" SET DEFAULT 0,
ALTER COLUMN "videoMinutes" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "screenShareMinutes" SET DEFAULT 0,
ALTER COLUMN "screenShareMinutes" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Usage" ALTER COLUMN "audioMinutes" SET DEFAULT 0,
ALTER COLUMN "audioMinutes" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "videoMinutes" SET DEFAULT 0,
ALTER COLUMN "videoMinutes" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "screenShareMinutes" SET DEFAULT 0,
ALTER COLUMN "screenShareMinutes" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "UsageSegment" ADD COLUMN     "audioMinutes" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "participants" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "screenShareMinutes" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "videoMinutes" DOUBLE PRECISION NOT NULL DEFAULT 0;
